<?php

/**
 * @file
 * Contains itc_jsonapi.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\itc_jsonapi\MenuLinkContentAccessControlHandler;

/**
 * Implements hook_help().
 */
function itc_jsonapi_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the itc_jsonapi module.
    case 'help.page.itc_jsonapi':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('jsonapi enhencers') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_type_build().
 */
function itc_jsonapi_entity_type_build(array &$entity_types) {
  if (isset($entity_types['menu_link_content'])) {
    /** @var \Drupal\Core\Entity\ContentEntityType $menu_link_content_type */
    $menu_link_content_type = $entity_types['menu_link_content'];
    $menu_link_content_type->setHandlerClass('access', MenuLinkContentAccessControlHandler::class);
  }
}
